### ISSUE TITLE
Drugs should be an array, not a string

### ISSUE THREAD

**Issue by dsifford** [aliemteam/aliemcards#102]
Drugs currently exist like this in the frontmatter.

```yml
[...]
updates: 2017/02/14
cateories:
    - Toxicology
drugs: amantadine, buproprion, chlorpromazine, desipramine, fluoxetine, labetalol, Methylphenidate, Phentermine  # ...etc
```
This creates extra work. 

It should be like this

```yml
[...]
updates: 2017/02/14
cateories:
    - Toxicology
drugs: [ amantadine, buproprion, chlorpromazine, desipramine, fluoxetine, labetalol, Methylphenidate, Phentermine ]
```
